#!/usr/bin/env python3
"""Bake a 2D city-clutter raster of the NoMa tile for the Outdoor 2D path-loss sim.

Projects the baked NoMa voxel grid top-down (a column is "building" if any voxel above ground is
solid) into a compact bit-packed 2D grid, and georeferences the four corners (vox_to_lonlat). The
Outdoor 2D solver marches the Tx→cell ray through this raster and adds a per-crossing clutter loss,
so predicted coverage bends around buildings instead of being pure log-distance.

Output  Data/noma_clutter.js:
  window.NOMA_CLUTTER = { nx, nz, cell_m, corners:{x0z0,x1z0,x0z1,x1z1:[lon,lat]}, grid_b64 }
"""
import sys, os, json, base64
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SIM = os.path.join(ROOT, "Physics Engine", "3D Map Physics", "SIM V1 3D")
sys.path.insert(0, SIM)
import voxelize_city as VC   # vox_to_lonlat

MAN = json.load(open(os.path.join(SIM, "city", "NoMa_FCC_tile", "manifest_3d.json")))
GRID_BIN = os.path.join(ROOT, "Unity_RF_Simulator/Unity_RF_Simulator/Build/WebGL/StreamingAssets/scene_outdoor_noma_grid.bin")
OUT = os.path.join(ROOT, "Data", "noma_clutter.js")

NX, NY, NZ = MAN["grid_shape"]
grid = np.fromfile(GRID_BIN, dtype=np.uint8).reshape(NX, NY, NZ)   # C-order (x,y,z)
# ground row (y=0) is often filled terrain; treat a column as building only if it rises above it
solid = grid != 0
clutter = solid[:, 1:, :].any(axis=1)          # (NX, NZ) bool — any solid voxel above ground
print("building columns:", int(clutter.sum()), "/", NX * NZ, f"({100*clutter.mean():.0f}%)")

corners = {name: [round(v, 7) for v in VC.vox_to_lonlat(MAN, x, z)]
           for name, (x, z) in {"x0z0": (0, 0), "x1z0": (NX - 1, 0),
                                "x0z1": (0, NZ - 1), "x1z1": (NX - 1, NZ - 1)}.items()}

bits = np.packbits(clutter.reshape(-1).astype(np.uint8))    # row-major over (x, then z)
payload = {"nx": NX, "nz": NZ, "cell_m": MAN["cell_size_m"], "corners": corners,
           "grid_b64": base64.b64encode(bits.tobytes()).decode()}
with open(OUT, "w") as f:
    f.write("// Generated by scripts/bake_noma_clutter.py — 2D building-clutter raster of the NoMa tile\n")
    f.write("// (top-down projection of the voxel grid), georeferenced by corner lon/lat. Bit-packed.\n")
    f.write("window.NOMA_CLUTTER = " + json.dumps(payload, separators=(",", ":")) + ";\n")

print(f"corners: {corners}")
print(f"wrote {OUT}  ({os.path.getsize(OUT)//1024} KB)")
