#!/usr/bin/env python3
"""Bake the 7/24 outdoor NoMa walk to a compact JS global for the dashboard's Outdoor views.

Keeps each measurement's network / band / PCI / channel so the Coverage sidebar can FILTER the
outdoor dots (and a 2D sim can score a specific PCI). The raw "carrier" field is a BAND
description, not the operator, so the operator is derived from PCI via the base-station catalog
(Data/base_stations.js). Deduped to (location, operator, network, band, pci, channel) with mean
RSRP, and packed (interned string tables + numeric point rows) to stay small.

Output  Data/outdoor_walk.js:
  window.OUTDOOR_WALK = {
    fcc:{lon,lat}, n,
    ops:[...], nets:[...], bands:[...], chs:[...],           # interned lookup tables
    pts:[[lon,lat,rsrp,pci,opIdx,netIdx,bandIdx,chIdx], ...],
    facets:{operators,networks,bands,pcis,channels}          # distinct values, for the filters
  }
"""
import re, json, os, statistics, argparse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Defaults reproduce the built-in 7/24 NoMa bake; the project backend
# (Backend/server/pipeline.py) passes an uploaded outdoor walk via --src/--out.
_ap = argparse.ArgumentParser(description="Bake an outdoor walk records file to window.OUTDOOR_WALK")
_ap.add_argument("--src", default=os.path.join(ROOT, "FCC_Walk_Outdoor_Indoor_Full/Outdoor_Walk_Test_7-24/records_data.js"),
                 help="a records_data.js-style file (const records = [...]) with lon/lat/rsrp/pci")
_ap.add_argument("--bs", default=os.path.join(ROOT, "Data/base_stations.js"),
                 help="base_stations.js for the PCI->operator join")
_ap.add_argument("--out", default=os.path.join(ROOT, "Data/outdoor_walk.js"))
_ap.add_argument("--fcc-lon", type=float, default=-77.00740)
_ap.add_argument("--fcc-lat", type=float, default=38.90359)
_args = _ap.parse_args()
SRC, BS, OUT = _args.src, _args.bs, _args.out
FCC = {"lon": _args.fcc_lon, "lat": _args.fcc_lat}

# PCI -> operator, from the base-station catalog (a PCI is a sector of one operator's site).
pci_op = {}
bs = json.loads(re.search(r"window\.BASE_STATIONS\s*=\s*(\[.*\])\s*;?\s*$", open(BS).read(), re.S).group(1))
for site in bs:
    for sec in site.get("sectors", []):
        if sec.get("pci") is not None and sec.get("carrier"):
            pci_op.setdefault(int(sec["pci"]), sec["carrier"])

recs = json.loads(re.search(r"const records\s*=\s*(\[.*\])\s*;?\s*$", open(SRC).read(), re.S).group(1))

def s(v, d=""):
    return str(v).strip() if v not in (None, "") else d

cells = {}
for r in recs:
    # accept both the outdoor bake's avg_rsrp and build_all_bands_data's rsrp
    lat, lon = r.get("latitude"), r.get("longitude")
    rsrp = r.get("avg_rsrp", r.get("rsrp"))
    if lat is None or lon is None or rsrp is None:
        continue
    try:
        pci = int(float(r.get("pci")))
    except (TypeError, ValueError):
        continue
    op = pci_op.get(pci, "other")
    net, band, ch = s(r.get("network"), "?"), s(r.get("band"), "?"), s(r.get("freq"))
    key = (round(lat, 5), round(lon, 5), op, net, band, pci, ch)
    cells.setdefault(key, []).append(float(rsrp))

# interned tables
ops, nets, bands, chs = [], [], [], []
def idx(tbl, v):
    if v not in tbl:
        tbl.append(v)
    return tbl.index(v)

rows = []
for (lat, lon, op, net, band, pci, ch), v in cells.items():
    rows.append([round(lon, 5), round(lat, 5), round(statistics.mean(v), 1), pci,
                 idx(ops, op), idx(nets, net), idx(bands, band), idx(chs, ch)])
rows.sort(key=lambda r: (r[4], r[6], r[3]))

payload = {
    "fcc": FCC, "n": len(rows), "ops": ops, "nets": nets, "bands": bands, "chs": chs, "pts": rows,
    "facets": {
        "operators": sorted(set(ops)), "networks": sorted(set(nets)),
        "bands": sorted({b for b in bands if b != "?"}, key=lambda x: (len(x), x)),
        "pcis": sorted({r[3] for r in rows}), "channels": sorted({c for c in chs if c}, key=lambda x: (len(x), x)),
    },
}
with open(OUT, "w") as f:
    f.write("// Generated by scripts/bake_outdoor_walk.py — the 7/24 NoMa outdoor walk, tagged with\n")
    f.write("// operator/network/band/PCI/channel (operator via PCI->base_stations) so the Coverage\n")
    f.write("// sidebar can filter the outdoor dots. Packed: interned tables + numeric point rows.\n")
    f.write("window.OUTDOOR_WALK = " + json.dumps(payload, separators=(",", ":")) + ";\n")

print(f"baked {len(rows)} points (from {len(recs)} records) -> {OUT}")
print(f"file size: {os.path.getsize(OUT)//1024} KB")
print("facets:", {k: len(v) for k, v in payload['facets'].items()}, "| operators:", payload['facets']['operators'])
