#!/usr/bin/env python3
"""Bake the 7/24 outdoor NoMa walk TIME-SERIES to a compact JS global for the dashboard's
Outdoor "Time Elapse" tab (Frontend/osm3d/outdoor_timelapse.html).

This is the time-ordered sibling of scripts/bake_outdoor_walk.py: instead of position-averaged
cells, it keeps every raw per-measurement sample WITH its elapsed time (t_sec) so the tab can
replay the walk chronologically (scrub / play), exactly like the indoor Time Elapse which reads
Data/timeseries_data.js.

Like the walk bake, each sample's operator is derived from PCI via the base-station catalog
(the raw "carrier" field is a BAND description, not the operator). All four metrics are kept
(rsrp/rsrq/cinr/rssi) so the tab's metric selector can switch between them. Packed as interned
string tables + numeric rows, sorted by time.

Output  Data/outdoor_timeseries.js:
  window.OUTDOOR_TIMESERIES = {
    startTime:"ISO-8601", fcc:{lon,lat}, n, maxTSec,
    ops:[...], nets:[...], bands:[...], chs:[...],                 # interned lookup tables
    pts:[[t_sec, lon, lat, rsrp, rsrq, cinr, rssi, pci,
          opIdx, netIdx, bandIdx, chIdx], ...],                   # sorted by t_sec
    facets:{operators,networks,bands,pcis,channels}               # distinct values, for the filters
  }
"""
import re, json, os, argparse

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Defaults reproduce the built-in 7/24 NoMa bake; the project backend passes an uploaded
# outdoor timeseries via --src/--out.
_ap = argparse.ArgumentParser(description="Bake an outdoor timeseries file to window.OUTDOOR_TIMESERIES")
_ap.add_argument("--src", default=os.path.join(ROOT, "FCC_Walk_Outdoor_Indoor_Full/Outdoor_Walk_Test_7-24/timeseries_data.js"),
                 help="a timeseries_data.js-style file (timeseriesRecords = [...]) with t_sec/lon/lat/rsrp/pci")
_ap.add_argument("--bs", default=os.path.join(ROOT, "Data/base_stations.js"))
_ap.add_argument("--out", default=os.path.join(ROOT, "Data/outdoor_timeseries.js"))
_ap.add_argument("--fcc-lon", type=float, default=-77.00740)
_ap.add_argument("--fcc-lat", type=float, default=38.90359)
_args = _ap.parse_args()
SRC, BS, OUT = _args.src, _args.bs, _args.out
FCC = {"lon": _args.fcc_lon, "lat": _args.fcc_lat}

# PCI -> operator, from the base-station catalog (a PCI is a sector of one operator's site).
pci_op = {}
bs = json.loads(re.search(r"window\.BASE_STATIONS\s*=\s*(\[.*\])\s*;?\s*$", open(BS).read(), re.S).group(1))
for site in bs:
    for sec in site.get("sectors", []):
        if sec.get("pci") is not None and sec.get("carrier"):
            pci_op.setdefault(int(sec["pci"]), sec["carrier"])

raw = open(SRC).read()
start = re.search(r'timeseriesStartTime\s*=\s*"([^"]+)"', raw)
start_time = start.group(1) if start else None
recs = json.loads(re.search(r"timeseriesRecords\s*=\s*(\[.*\])\s*;", raw, re.S).group(1))


def s(v, d=""):
    return str(v).strip() if v not in (None, "") else d


# interned tables (append-order preserved so an index is stable once assigned)
ops, nets, bands, chs = [], [], [], []


def idx(tbl, v):
    if v not in tbl:
        tbl.append(v)
    return tbl.index(v)


def num(v):
    try:
        f = float(v)
        return f if f == f else None  # drop NaN
    except (TypeError, ValueError):
        return None


rows = []
skipped = 0
for r in recs:
    t = num(r.get("t_sec"))
    lat, lon = num(r.get("latitude")), num(r.get("longitude"))
    rsrp = num(r.get("rsrp"))
    if t is None or lat is None or lon is None or rsrp is None:
        skipped += 1
        continue
    try:
        pci = int(float(r.get("pci")))
    except (TypeError, ValueError):
        skipped += 1
        continue
    op = pci_op.get(pci, "other")
    net, band, ch = s(r.get("network"), "?"), s(r.get("band"), "?"), s(r.get("freq"))

    def r1(v):
        return round(v, 1) if v is not None else None

    rows.append([
        round(t, 3), round(lon, 5), round(lat, 5),
        r1(rsrp), r1(num(r.get("rsrq"))), r1(num(r.get("cinr"))), r1(num(r.get("rssi"))),
        pci, idx(ops, op), idx(nets, net), idx(bands, band), idx(chs, ch),
    ])

rows.sort(key=lambda r: r[0])   # chronological — the tab plays back in this order
max_t = rows[-1][0] if rows else 0.0

payload = {
    "startTime": start_time, "fcc": FCC, "n": len(rows), "maxTSec": max_t,
    "ops": ops, "nets": nets, "bands": bands, "chs": chs, "pts": rows,
    "facets": {
        "operators": sorted(set(ops)),
        "networks": sorted(set(nets)),
        "bands": sorted({b for b in bands if b != "?"}, key=lambda x: (len(x), x)),
        "pcis": sorted({r[7] for r in rows}),
        "channels": sorted({c for c in chs if c}, key=lambda x: (len(x), x)),
    },
}

with open(OUT, "w") as f:
    f.write("// Generated by scripts/bake_outdoor_timeseries.py — the time-ordered 7/24 NoMa outdoor\n")
    f.write("// walk (every raw sample + elapsed t_sec), tagged with operator/network/band/PCI/channel\n")
    f.write("// (operator via PCI->base_stations). Drives the Outdoor 'Time Elapse' tab's chronological\n")
    f.write("// replay. Packed: interned tables + numeric point rows sorted by time.\n")
    f.write("window.OUTDOOR_TIMESERIES = " + json.dumps(payload, separators=(",", ":")) + ";\n")

print(f"baked {len(rows)} samples (skipped {skipped}) from {len(recs)} records -> {OUT}")
print(f"start: {start_time} · maxTSec: {max_t:.1f}s ({max_t/60:.1f} min)")
print(f"file size: {os.path.getsize(OUT)//1024} KB")
print("facets:", {k: len(v) for k, v in payload['facets'].items()}, "| operators:", payload['facets']['operators'])
