#!/usr/bin/env python3
"""PR #26 — export the 2D O2I predictions + cross-validation to a browser asset for the
Map Coverage overlay (Data/pl2d_crossval.js).

For every prediction in pathloss_2d/out/metrics_bs_*.npz, this renders the predicted RSRP
grid to a transparent-outside PNG (data URI, exactly the 515×1150 floor-plan frame, so it
drops straight onto the Map Coverage plot), samples it at the measured points, level-
calibrates, and bundles the per-point residuals + stats:

  window.PL2D_CROSSVAL = {
    "lte_13_396": { label, freq_mhz, bearing_deg, distance_m, vmin, vmax, rsrp_png,
                    level_cal_db, rmse_after_cal_db, spearman_rho, n,
                    measured_mean, points:[{px,py,meas,pred_cal,resid}] }, ... }
  window.PL2D_CROSSVAL_KEYS = ["lte_13_396", ...]   // for the selector

usage: python export_web.py            # all predictions in out/
"""
from __future__ import annotations
import base64
import io
import json
import sys
from pathlib import Path

import numpy as np
from matplotlib import cm
from PIL import Image

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
OUT = HERE / "out"
WEB_JS = REPO / "Data" / "pl2d_crossval.js"
sys.path.insert(0, str(REPO / "Physics Engine" / "Cross_Validation" / "validation"))
import validate as V   # load_records, measured_points, sample_bilinear, spearman_rho


def rsrp_to_png_datauri(rsrp, outside, vmin, vmax):
    norm = np.clip((rsrp - vmin) / (vmax - vmin), 0, 1)
    rgba = (cm.viridis(norm) * 255).astype(np.uint8)     # (H,W,4)
    rgba[outside, 3] = 0                                  # transparent outside the envelope
    buf = io.BytesIO()
    Image.fromarray(rgba, "RGBA").save(buf, "PNG")
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def build_entry(npz_path, records):
    d = np.load(npz_path, allow_pickle=True)
    rsrp, outside = d["rsrp"], d["outside"]
    meta = json.loads(str(d["meta"]))
    pci, band, network = meta["pci"], meta["band"], meta["network"]
    ind = ~outside
    vmin = float(np.percentile(rsrp[ind], 2)); vmax = float(np.percentile(rsrp[ind], 98))

    recs = V.measured_points(records, network, band, pci)
    px = np.array([r["px"] for r in recs]); py = np.array([r["py"] for r in recs])
    meas = np.array([r["rsrp"] for r in recs])
    pred = V.sample_bilinear(rsrp, px, py)
    bias = float((meas - pred).mean())
    pred_cal = pred + bias
    resid = meas - pred_cal
    rho = V.spearman_rho(meas, pred)

    pts = [{"px": round(float(px[i]), 1), "py": round(float(py[i]), 1),
            "meas": round(float(meas[i]), 1), "pred_cal": round(float(pred_cal[i]), 1),
            "resid": round(float(resid[i]), 1)} for i in range(len(recs))]
    key = f"{network}_{band}_{pci}"
    entry = dict(
        key=key,
        label=f"{meta['site_id']} · PCI {pci} · B{band} · {meta['freq_mhz']:.0f} MHz",
        freq_mhz=meta["freq_mhz"], bearing_deg=meta.get("bearing_deg"),
        distance_m=meta.get("distance_m"),
        vmin=round(vmin, 1), vmax=round(vmax, 1),
        level_cal_db=round(bias, 1),
        rmse_after_cal_db=round(float(resid.std()), 1),
        spearman_rho=round(rho, 3) if rho is not None else None,
        n=len(recs), measured_mean=round(float(meas.mean()), 1),
        rsrp_png=rsrp_to_png_datauri(rsrp, outside, vmin, vmax),
        points=pts,
    )
    return key, entry


def main():
    records = V.load_records()
    npzs = sorted(OUT.glob("metrics_bs_*.npz"))
    if not npzs:
        raise SystemExit("no predictions in out/; run predict_o2i.py first")
    entries = {}
    for p in npzs:
        try:
            key, entry = build_entry(p, records)
            entries[key] = entry
            print(f"{key:16} n={entry['n']:>3}  rho={entry['spearman_rho']}  "
                  f"rmse_cal={entry['rmse_after_cal_db']} dB  level_cal={entry['level_cal_db']} dB")
        except SystemExit as e:
            print(f"skip {p.name}: {e}")
    keys = sorted(entries)
    WEB_JS.parent.mkdir(parents=True, exist_ok=True)
    with WEB_JS.open("w", encoding="utf-8") as f:
        f.write("// Generated by Cross_Validation/pathloss_2d/export_web.py — 2D O2I predicted-vs-measured\n")
        f.write("// RSRP for the Map Coverage overlay (PR #26). rsrp_png is a transparent-outside\n")
        f.write("// viridis heatmap in the 515x1150 floor-plan frame; points carry per-point residuals.\n")
        f.write("window.PL2D_CROSSVAL = " + json.dumps(entries, ensure_ascii=True) + ";\n")
        f.write("window.PL2D_CROSSVAL_KEYS = " + json.dumps(keys, ensure_ascii=True) + ";\n")
    print(f"-> {WEB_JS}  ({WEB_JS.stat().st_size/1e3:.0f} KB, {len(keys)} base stations)")


if __name__ == "__main__":
    main()
