"""pipeline.py — turn raw project uploads into a project's data files.

Shells out to the EXISTING repo scripts (no physics re-implementation) and writes the small
`Data/*.js`-style files the dashboard boots from into a project's data/ dir. Indoor·2D is the
fully-wired path (the user's primary "make the 2D pipeline" ask):

    CSV folder + floor-plan PNG + MapInfo .TAB
        -> parse GCPs from the TAB
        -> build_all_bands_data.py --csv-dir --gcps      -> records_data.js + timeseries_data.js
        -> base64 the PNG                                 -> floorplan_image.js
        -> affine px->lon/lat from the GCPs               -> floorplan_meta.js
        -> reuse the shared base-station catalog          -> base_stations.js
        (optional) prepare_indoor_basemap.py cropped to the TAB bbox -> basemap_image.js

Outdoor·2D and 3D dispatch here too; their bakes (bake_outdoor_*, voxelize*) are wired as
follow-on work — create() raises a clear error for them so the API responds honestly.
"""
from __future__ import annotations

import base64
import json
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np

import validate  # sibling module (Backend/server on sys.path)

REPO_ROOT = Path(__file__).resolve().parents[2]
BUILD_ALL_BANDS = REPO_ROOT / "ARCHIVE" / "EARLY Analysis" / "build_all_bands_data.py"
PREPARE_BASEMAP = REPO_ROOT / "scripts" / "prepare_indoor_basemap.py"
BAKE_OUTDOOR_WALK = REPO_ROOT / "scripts" / "bake_outdoor_walk.py"
BAKE_OUTDOOR_TS = REPO_ROOT / "scripts" / "bake_outdoor_timeseries.py"
SIM3D_DIR = REPO_ROOT / "Physics Engine" / "3D Map Physics" / "SIM V1 3D"
VOXELIZE = SIM3D_DIR / "voxelize.py"
EXPORT_WEB3 = SIM3D_DIR / "export_web3.py"
DEFAULT_BASE_STATIONS = "Data/base_stations.js"   # shared catalog, reused by new projects


class PipelineError(RuntimeError):
    pass


def fit_affine_px_to_lonlat(gcps: list[tuple]) -> list[list[float]]:
    """[[a,b,c],[d,e,f]] with lon=a·px+b·py+c, lat=d·px+e·py+f, least-squares over GCPs."""
    A = np.array([[g[2], g[3], 1.0] for g in gcps])
    lon = np.linalg.lstsq(A, np.array([g[0] for g in gcps]), rcond=None)[0]
    lat = np.linalg.lstsq(A, np.array([g[1] for g in gcps]), rcond=None)[0]
    return [[float(lon[0]), float(lon[1]), float(lon[2])],
            [float(lat[0]), float(lat[1]), float(lat[2])]]


def write_floorplan_image_js(png: Path, out_js: Path) -> tuple[int, int]:
    """Base64-embed the plan PNG as `const floorPlanImage = {...}` (Plotly image object).
    Returns (width, height)."""
    from PIL import Image
    with Image.open(png) as im:
        w, h = im.size
    b64 = base64.b64encode(png.read_bytes()).decode("ascii")
    out_js.write_text(
        "// Generated by Backend/server/pipeline.py — floor-plan raster for the Map Coverage view.\n"
        "    const floorPlanImage = {\n"
        f"          source: 'data:image/png;base64,{b64}',\n"
        "          xref: 'x', yref: 'y', x: 0, y: 0,\n"
        f"          sizex: {w}, sizey: {h},\n"
        "          xanchor: 'left', yanchor: 'top',\n"
        "          sizing: 'stretch', layer: 'below'\n"
        "    };\n", encoding="utf-8")
    return w, h


def write_floorplan_meta_js(gcps: list[tuple], w: int, h: int, out_js: Path) -> None:
    """window.FLOORPLAN_META with the px->lon/lat affine + GCPs (matches Data/floorplan_meta.js
    keys the dashboard reads: affine_px_to_lonlat, grid_shape, gcps, origin_lonlat)."""
    aff = fit_affine_px_to_lonlat(gcps)
    lon0 = float(np.mean([g[0] for g in gcps]))
    lat0 = float(np.mean([g[1] for g in gcps]))
    meta = {
        "source": "imported",
        "grid_shape": [h, w],
        "affine_px_to_lonlat": aff,
        "origin_lonlat": [lon0, lat0],
        "gcps": [{"label": g[4] or f"Pt {i+1}", "px": [g[2], g[3]], "lon": g[0], "lat": g[1]}
                 for i, g in enumerate(gcps)],
        "note": "generated from the imported .TAB GCPs by Backend/server/pipeline.py",
    }
    out_js.write_text("window.FLOORPLAN_META = " + json.dumps(meta, indent=2) + ";\n",
                      encoding="utf-8")


def _run(cmd, what: str) -> subprocess.CompletedProcess:
    """Run a repo script as a subprocess (cwd=repo root); raise PipelineError on failure."""
    proc = subprocess.run([str(c) for c in cmd], capture_output=True, text=True, cwd=str(REPO_ROOT))
    if proc.returncode != 0:
        raise PipelineError(f"{what} failed:\n{proc.stderr[-2000:]}")
    return proc


def _resolve_csv_dir(files: dict) -> Path:
    csv_paths = files.get("csv") or []
    if not csv_paths:
        raise PipelineError("no measurement CSVs provided")
    if len(csv_paths) == 1 and Path(csv_paths[0]).is_dir():
        return Path(csv_paths[0])
    return Path(csv_paths[0]).parent


def run_build_all_bands(csv_dir: Path, gcps, out_records: Path,
                        out_timeseries: Path, any_csv: bool = False) -> None:
    """Run the parametrized build_all_bands_data.py. gcps=None -> the built-in default GCPs
    (fine for outdoor, where px/py from GCPs is unused — coverage is placed by lon/lat)."""
    cmd = [sys.executable, BUILD_ALL_BANDS, "--csv-dir", csv_dir,
           "--out-records", out_records, "--out-timeseries", out_timeseries]
    if gcps:
        cmd += ["--gcps", json.dumps([[g[0], g[1], g[2], g[3]] for g in gcps])]
    if any_csv:
        cmd.append("--any-csv")
    _run(cmd, "build_all_bands_data.py")
    if not Path(out_records).is_file() or Path(out_records).stat().st_size < 40:
        raise PipelineError("build_all_bands_data.py produced no records (check CSV format/columns)")


def create_indoor_2d(data_dir: Path, files: dict, opts: dict) -> list[dict]:
    """Run the indoor·2D pipeline; write data files into data_dir; return the manifest data list."""
    csv_paths = files.get("csv") or []
    csv_dir = csv_paths[0] if (len(csv_paths) == 1 and Path(csv_paths[0]).is_dir()) \
        else (Path(csv_paths[0]).parent if csv_paths else None)
    if not csv_dir:
        raise PipelineError("no measurement CSVs provided")
    png = Path(files["image"][0])
    tab = Path(files["tab"][0])
    gcps = validate.parse_tab_gcps(tab.read_text(encoding="latin-1", errors="replace"))
    if len(gcps) < 3:
        raise PipelineError(f"TAB needs >= 3 GCPs, found {len(gcps)}")

    w, h = write_floorplan_image_js(png, data_dir / "floorplan_image.js")
    write_floorplan_meta_js(gcps, w, h, data_dir / "floorplan_meta.js")
    run_build_all_bands(Path(csv_dir), gcps,
                        data_dir / "records_data.js", data_dir / "timeseries_data.js",
                        any_csv=bool(opts.get("any_csv")))

    return [
        {"role": "records",      "src": "stored:records_data.js"},
        {"role": "timeseries",   "src": "stored:timeseries_data.js"},
        {"role": "floorplan",    "src": "stored:floorplan_image.js"},
        {"role": "meta",         "src": "stored:floorplan_meta.js"},
        {"role": "baseStations", "src": DEFAULT_BASE_STATIONS},   # reuse shared catalog
    ]


# Indoor base data every created project reuses so the dashboard initializes (its indoor plot is
# hidden in outdoor mode; the 3D viewer keeps the 2D heatmap under the 3D toggle).
_INDOOR_BASE_REUSE = [
    {"role": "records",      "src": "Data/records_data.js"},
    {"role": "timeseries",   "src": "Data/timeseries_data.js"},
    {"role": "floorplan",    "src": "Data/floorplan_image.js"},
    {"role": "meta",         "src": "Data/floorplan_meta.js"},
    {"role": "baseStations", "src": DEFAULT_BASE_STATIONS},
]


def create_outdoor_2d(data_dir: Path, files: dict, opts: dict) -> list[dict]:
    """Uploaded outdoor scanner CSVs -> outdoor_walk.js + outdoor_timeseries.js (packed for the
    Outdoor Map Coverage + Time Elapse iframes). Reuses the shared base-station catalog for the
    PCI->operator join."""
    csv_dir = _resolve_csv_dir(files)
    tmp = data_dir / "_tmp"
    tmp.mkdir(parents=True, exist_ok=True)
    rec, ts = tmp / "records.js", tmp / "timeseries.js"
    run_build_all_bands(csv_dir, None, rec, ts, any_csv=bool(opts.get("any_csv")))
    bs = REPO_ROOT / DEFAULT_BASE_STATIONS
    _run([sys.executable, BAKE_OUTDOOR_WALK, "--src", rec, "--bs", bs,
          "--out", data_dir / "outdoor_walk.js"], "bake_outdoor_walk.py")
    _run([sys.executable, BAKE_OUTDOOR_TS, "--src", ts, "--bs", bs,
          "--out", data_dir / "outdoor_timeseries.js"], "bake_outdoor_timeseries.py")
    ow = data_dir / "outdoor_walk.js"
    if not ow.is_file() or ow.stat().st_size < 60:
        raise PipelineError("no outdoor walk points produced (check the CSV lon/lat/pci columns)")
    return _INDOOR_BASE_REUSE + [
        {"role": "outdoorWalk",       "src": "stored:outdoor_walk.js"},
        {"role": "outdoorTimeseries", "src": "stored:outdoor_timeseries.js"},
    ]


def create_3d(data_dir: Path, files: dict, opts: dict, env: str) -> list[dict]:
    """Voxelize the uploaded model (honoring the elevation option) -> material grid + SIM3D web
    assets. The dashboard boots on the indoor base; the 3D viewer/sim consume the project model +
    grid (the deep viewer/sim render wiring is the follow-on task noted in export_web3.py)."""
    models = files.get("model") or []
    if not models:
        raise PipelineError("no 3D model provided")
    mesh = next((Path(p) for p in models if Path(p).suffix.lower() in
                 {".obj", ".glb", ".gltf", ".dae", ".fbx", ".3ds", ".stl", ".kmz"}), Path(models[0]))
    model_dir = data_dir / "model"
    model_dir.mkdir(parents=True, exist_ok=True)
    for p in models:                       # keep companion .mtl / textures beside the mesh
        shutil.copy2(p, model_dir / Path(p).name)

    cell = float(opts.get("cell_m") or 1.0)
    vox_dir = data_dir / "vox"
    vox_dir.mkdir(parents=True, exist_ok=True)
    cmd = [sys.executable, VOXELIZE, "--obj", model_dir / mesh.name, "--cell", cell, "--out", vox_dir]
    if (opts.get("elevation") or {}).get("mode") == "floor":
        cmd.append("--seal-ceiling")       # bounded slab: seal the top so the interior is watertight
    _run(cmd, "voxelize.py")
    if not (vox_dir / "material_grid.npy").is_file():
        raise PipelineError("voxelize.py produced no material grid")
    # export_web3 reads manifest_3d.json from --sim-dir; voxelize writes it into vox_dir.
    _run([sys.executable, EXPORT_WEB3, "--sim-dir", vox_dir,
          "--out", data_dir / "sim_assets_3d.js", "--global", "SIM3D_ASSETS"], "export_web3.py")
    return _INDOOR_BASE_REUSE + [
        {"role": "sim3dAssets", "src": "stored:sim_assets_3d.js"},
    ]


def create(store_root: Path, pid: str, mode: dict, label: str,
           files: dict, opts: dict) -> dict:
    """Build a project on disk and return its manifest. Dispatch by mode."""
    env, dim = mode.get("environment"), mode.get("dim")
    proj_dir = store_root / pid
    data_dir = proj_dir / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    if env == "indoor" and dim == "2d":
        data = create_indoor_2d(data_dir, files, opts)
    elif env == "outdoor" and dim == "2d":
        data = create_outdoor_2d(data_dir, files, opts)
    elif dim == "3d":
        data = create_3d(data_dir, files, opts, env)
    else:
        raise PipelineError(f"unsupported mode: {env}·{dim}")

    manifest = {
        "id": pid, "label": label, "environment": env, "dim": dim,
        "builtin": False,
        # AI/ML surrogates (ONNX) are trained on the DEFAULT dataset only, so they're invalid for a
        # created project. The Simulation tab honors this flag (non-AI/ML solvers only); see docs/ai-ml.
        "ai_ml": False,
        "data": data, "opts": opts,
    }
    if env == "outdoor":
        manifest["iframes"] = {
            "map":  "Map%20Coverage/outdoor_view.html?v=osm3d-three1",
            "time": "Time%20Elapse/outdoor_timelapse.html",
        }
    (proj_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return manifest
