#!/usr/bin/env python3
"""Bake the 7/24 outdoor NoMa walk to a small JS global for the dashboard's Outdoor views.

Reads the raw records (28k measurements across bands/PCIs) from the outdoor walk export,
dedupes to unique physical locations (~1 m grid) with the mean RSRP, and writes
Data/outdoor_walk.js: window.OUTDOOR_WALK = { fcc:{lon,lat}, points:[{lon,lat,rsrp}] }.
The whole walk path (every visited location), not per-sector.
"""
import re, json, os, statistics

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "FCC_Walk_Outdoor_Indoor_Full/Outdoor_Walk_Test_7-24/records_data.js")
OUT = os.path.join(ROOT, "Data/outdoor_walk.js")
FCC = {"lon": -77.00740, "lat": 38.90359}   # FCC HQ 7th-floor walk centre (from osm_buildings_view.html)

txt = open(SRC).read()
recs = json.loads(re.search(r"const records\s*=\s*(\[.*\])\s*;?\s*$", txt, re.S).group(1))

# dedupe to ~1 m cells, mean RSRP per cell (the physical path)
cells = {}
for r in recs:
    lat, lon, rsrp = r.get("latitude"), r.get("longitude"), r.get("avg_rsrp")
    if lat is None or lon is None or rsrp is None:
        continue
    key = (round(lat, 5), round(lon, 5))
    cells.setdefault(key, []).append(float(rsrp))

points = [{"lon": lon, "lat": lat, "rsrp": round(statistics.mean(v), 1)}
          for (lat, lon), v in cells.items()]
points.sort(key=lambda p: (p["lat"], p["lon"]))

payload = {"fcc": FCC, "n": len(points), "points": points}
with open(OUT, "w") as f:
    f.write("// Generated by scripts/bake_outdoor_walk.py — the 7/24 NoMa outdoor walk (whole path),\n")
    f.write("// deduped to ~1 m locations with mean RSRP. Used by the dashboard's Outdoor 2D/3D views.\n")
    f.write("window.OUTDOOR_WALK = " + json.dumps(payload, separators=(",", ":")) + ";\n")

print(f"baked {len(points)} unique walk locations (from {len(recs)} records) -> {OUT}")
print(f"file size: {os.path.getsize(OUT)//1024} KB")
